import type { Title } from './types';
export const backdrop = 'https://cdn.mos.cms.futurecdn.net/LVoJnXBbUH6xx9EkfgVnc5.jpg';
export const catalog: Title[] = [
 {id:'258687',title:'Интерстеллар',original:'Interstellar',type:'movie',year:2014,genre:'Фантастика',plot:'Когда Земля перестаёт быть домом, команда исследователей отправляется за пределы нашей галактики в поисках будущего для человечества.',poster:'https://www.originalfilmart.com/cdn/shop/products/interstellar_2014_advance_original_film_art_682852f2-23f6-46de-a1db-4029d5b6f0b4.jpg?v=1574284010&width=1200',quality:0},
 {id:'447301',title:'Начало',original:'Inception',type:'movie',year:2010,genre:'Триллер',plot:'Специалист по проникновению в чужие сны получает задание, которое кажется невозможным: не украсть идею, а заронить её в сознание.',poster:'https://artofthemovies.co.uk/cdn/shop/files/inception_advance_SD18120_B-731214_920c5dfe-8d66-47c7-af74-11b98a83ebbf_1024x1024%402x.jpg?v=1737545739',quality:0},
 {id:'1032606',title:'Тьма',original:'Dark',type:'serial',year:2017,genre:'Детектив',plot:'Исчезновение детей в немецком городке связывает судьбы четырёх семей и открывает тайну, в которой прошлое и будущее неразделимы.',poster:'https://image.pmgstatic.com/cache/resized/w663/files/images/film/posters/163/939/163939457_87347a.jpg',quality:0},
 {id:'4540126',title:'Дюна: Часть вторая',original:'Dune: Part Two',type:'movie',year:2024,genre:'Фантастика',plot:'Пол Атрейдес присоединяется к фременам. Среди песков Арракиса ему предстоит выбрать между личным чувством и судьбой целой вселенной.',poster:'https://i0.wp.com/thecontributor.org/wp-content/uploads/2024/03/Dune-Part2.jpg?fit=1170%2C1707&ssl=1',quality:0},
 {id:'demo-sintel',title:'Синтел',original:'Sintel',type:'movie',year:2010,genre:'Фэнтези',plot:'Девушка ищет потерянного дракона. Открытый фильм Blender Studio. Бесплатный демонстрационный поток: оригинальная дорожка и доступные субтитры. Русской озвучки здесь нет.',poster:'https://upload.wikimedia.org/wikipedia/commons/f/f3/Sintel_Poster_Paintover_clean.jpg',quality:2160,demo:true}
];
