'use client';
import { useEffect, useMemo, useState } from 'react';
import { Search, Play, ArrowUpRight, Bookmark, Settings2, Check, X, LoaderCircle, Film } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { catalog, backdrop } from '@/lib/cinema/catalog';
import { Player } from '@/components/cinema/player';
import {detail,playback} from '@/lib/cinema/provider';
import type { Title, Detail, Playback, Episode } from '@/lib/cinema/types';

type HistoryItem={id:string;key:string;time:number;duration:number};
export default function Home(){
 const [tab,setTab]=useState('Главная'),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[genre,setGenre]=useState('Все жанры');
 const [saved,setSaved]=useState<string[]>([]),[history,setHistory]=useState<HistoryItem[]>([]),[settings,setSettings]=useState(false);
 const [selected,setSelected]=useState<Title|null>(null),[details,setDetails]=useState<Detail|null>(null),[episode,setEpisode]=useState<Episode|null>(null),[stream,setStream]=useState<Playback|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[playing,setPlaying]=useState(false),[loadAttempt,setLoadAttempt]=useState(0);
 const [idQuery,setIdQuery]=useState(''),[extra,setExtra]=useState<Title[]>([]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem('kadr:saved')||'[]');const h=JSON.parse(localStorage.getItem('kadr:history')||'[]');if(Array.isArray(s))setSaved(s.filter(x=>typeof x==='string'));if(Array.isArray(h))setHistory(h.filter(x=>x&&typeof x.id==='string'&&Number.isFinite(x.time)));}catch{}},[]);
 const all=useMemo(()=>[...catalog,...extra],[extra]);
 const titles=useMemo(()=>all.filter(t=>(tab!=='Фильмы'||t.type==='movie')&&(tab!=='Сериалы'||t.type==='serial')&&(tab!=='Моё'||saved.includes(t.id))&&(genre==='Все жанры'||t.genre===genre)&&`${t.title} ${t.original}`.toLowerCase().includes(query.toLowerCase())),[all,tab,saved,genre,query]);
 function openTitle(t:Title){setSelected(t);setDetails(null);setEpisode(null);setStream(null);setError('');setPlaying(false);}
 function toggleSave(id:string){setSaved(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];try{localStorage.setItem('kadr:saved',JSON.stringify(next));}catch{}return next;});}
 useEffect(()=>{if(!selected)return;const abort=new AbortController();setLoading(true);setError('');detail(selected.id,abort.signal).then(d=>{setDetails(d);let previous:string|undefined;try{previous=(JSON.parse(localStorage.getItem('kadr:history')||'[]') as HistoryItem[]).find(h=>h.id===selected.id)?.key;}catch{}setEpisode(d.episodes.find(e=>e.key===previous)??d.episodes[0]??null);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[selected,loadAttempt]);
 useEffect(()=>{if(!selected||!episode||!playing)return;const abort=new AbortController();setLoading(true);setError('');setStream(null);playback(selected.id,episode.season,episode.number,abort.signal).then(setStream).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[selected,episode,playing,loadAttempt]);
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(x:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context)return;const abort=new AbortController();
  try{Promise.resolve(context.registerTool({name:'search_catalog',description:'Search the cinema catalogue and show matching titles on screen.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:150}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||!('query'in input)||typeof input.query!=='string'||input.query.length>150)throw new Error('query must be a string up to 150 characters');const query=input.query;setQuery(query);setSearchOpen(true);setTab('Главная');setGenre('Все жанры');return {items:catalog.filter(t=>(t.title+' '+t.original).toLowerCase().includes(query.toLowerCase())).map(t=>({id:t.id,title:t.title}))};}},{signal:abort.signal})).catch(()=>{});}catch{}
  return()=>abort.abort();
 },[]);
 const feature=catalog[0];
 function updateProgress(time:number,duration:number){if(!selected||!episode||!Number.isFinite(time)||!Number.isFinite(duration)||time<1||duration<1)return;const item={id:selected.id,key:episode.key,time,duration};try{localStorage.setItem(`kadr:progress:${item.id}:${item.key}`,JSON.stringify(item));}catch{}setHistory(prev=>{const next=[item,...prev.filter(x=>x.id!==item.id)].slice(0,30);try{localStorage.setItem('kadr:history',JSON.stringify(next));}catch{}return next;});}
 async function openId(){if(!/^\d{1,10}$/.test(idQuery)){setError('Введите числовой ID Кинопоиска.');return;}const t=all.find(x=>x.id===idQuery)??{id:idQuery,title:`Кинопоиск #${idQuery}`,original:'',type:'movie' as const,year:0,genre:'',plot:'Информация загружается от источника.',poster:'',quality:0};setSettings(false);openTitle(t);}
 useEffect(()=>{if(details&&!catalog.some(t=>t.id===details.item.id))setExtra(prev=>[...prev.filter(t=>t.id!==details.item.id),details.item]);},[details]);
 return <main className="cinema">
 <header className="topbar"><a className="brand" href="/" aria-label="Кадр — главная">кадр<span>•</span></a><nav aria-label="Каталог">{['Главная','Фильмы','Сериалы','Моё'].map(t=><button key={t} onClick={()=>{setTab(t);setGenre('Все жанры');}} className={tab===t?'active':''} aria-current={tab===t?'page':undefined}>{t}</button>)}</nav><div className="header-actions">{searchOpen?<label className="search-box"><Search size={16}/><input autoFocus aria-label="Найти фильм или сериал" placeholder="Название фильма" value={query} maxLength={150} onChange={e=>setQuery(e.target.value)}/><button aria-label="Закрыть поиск" onClick={()=>{setSearchOpen(false);setQuery('');}}><X size={14}/></button></label>:<button aria-label="Поиск" onClick={()=>setSearchOpen(true)}><Search size={20}/></button>}<button aria-label="Источник и настройки" onClick={()=>{setSettings(true);setError('');}}><Settings2 size={19}/></button><span className="avatar">У</span></div></header>
 {tab==='Главная'&&!query&&<><section className="intro"><div><p className="eyebrow">ВАШ ЛИЧНЫЙ КИНОЗАЛ</p><h1>Хороший вечер.<br/><span>Хорошее кино.</span></h1></div><p className="intro-note">Истории, в которые хочется<br/>погрузиться.</p></section><section className="featured"><div className="hero-art" style={{backgroundImage:`linear-gradient(90deg,#14201bfa 0%,#14201bd9 30%,#14201b00 85%),url("${backdrop}")`,backgroundSize:'cover',backgroundPosition:'center'}}/><div className="hero-content"><span className="pill">ВЫБОР РЕДАКЦИИ</span><p className="hero-original">INTERSTELLAR</p><h2>Интерстеллар</h2><div className="meta"><span>2014</span><span>Фантастика</span><span>2 ч 49 мин</span></div><p>За пределами возможного.<br/>Ради тех, кто остался дома.</p><button className="primary" onClick={()=>openTitle(feature)}><Play size={18} fill="currentColor"/>Открыть фильм</button></div><div className="hero-caption">01 / 04 <ArrowUpRight size={18}/></div></section></>}
 {tab==='Главная'&&!query&&history.some(h=>h.time/h.duration<.95)&&<section className="continue"><div className="section-heading"><h2>Продолжить просмотр</h2></div><div className="continue-list">{history.filter(h=>h.time/h.duration<.95).map(h=>{const t=all.find(x=>x.id===h.id);return t?<button className="filter" key={h.id} onClick={()=>openTitle(t)}><Play size={14}/>{t.title} · {Math.floor(h.time/60)} мин</button>:null;})}</div></section>}
 <section className="catalog"><div className="section-heading"><h2>{query?`Результаты поиска`:tab==='Моё'?'Буду смотреть':tab==='Сериалы'?'Сериалы':tab==='Фильмы'?'Фильмы':'На вашем экране'}</h2><span>{titles.length} {titles.length===1?'история':'историй'}</span></div><div className="toolbar">{['Все жанры',...new Set(all.map(t=>t.genre).filter(Boolean))].map(g=><button className={'filter '+(genre===g?'selected':'')} key={g} onClick={()=>setGenre(g)} aria-pressed={genre===g}>{g}</button>)}<span className="catalog-note">Качество и дорожки проверяются перед просмотром</span></div><div className="movie-grid">{titles.map((m,i)=><article className="movie-card" key={m.id}><button className="poster-button" onClick={()=>openTitle(m)} aria-label={`Открыть ${m.title}`}><div className={'poster poster-'+i}>{m.poster?<img src={m.poster} alt={m.title} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.opacity='0';}}/>:<Film size={40}/>}<span className="poster-word">{m.original||m.title}</span>{m.demo&&<span className="quality">4K · ДЕМО</span>}{m.type==='serial'&&<span className="quality">СЕРИАЛ</span>}<span className="card-play"><Play fill="currentColor"/></span>{history.find(h=>h.id===m.id)&&<span className="progress-line" style={{width:`${Math.min(100,(history.find(h=>h.id===m.id)!.time/history.find(h=>h.id===m.id)!.duration)*100)}%`}}/>}</div></button><div className="card-heading"><button className="title-button" onClick={()=>openTitle(m)}><h3>{m.title}</h3></button><button className="save-button" aria-label={saved.includes(m.id)?`Удалить ${m.title} из Моего`:`Сохранить ${m.title}`} onClick={()=>toggleSave(m.id)}>{saved.includes(m.id)?<Check size={16}/>:<Bookmark size={16}/>}</button></div><p>{m.year||'—'} <span>·</span> {m.genre||'Кино'}</p></article>)}</div>{!titles.length&&<div className="empty"><Film size={28}/><p>{tab==='Моё'?'Сохраните фильм, и он появится здесь.':'Ничего не найдено. Попробуйте другое название или жанр.'}</p><button className="filter" onClick={()=>{setQuery('');setGenre('Все жанры');}}>Сбросить поиск</button></div>}<p className="notice catalog-footnote">Бесплатный источник может быть недоступен или не иметь 1080p. <button className="link" onClick={()=>{setSettings(true);setError('');}}>Об источнике</button></p></section>
 <footer><span className="brand small">кадр<span>•</span></span><p>Кино. И ничего лишнего.</p><span>Видео напрямую с источника · без хранения на сервере</span></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open){setSelected(null);setStream(null);setPlaying(false);}}}><DialogContent className="detail-dialog" showCloseButton={false}><DialogClose className="modal-close" aria-label="Закрыть фильм"><X size={20}/></DialogClose><DialogTitle className="sr-only">{details?.item.title||selected?.title}</DialogTitle><DialogDescription className="sr-only">Описание фильма, доступные серии и видеоплеер</DialogDescription>{selected&&<>{!playing&&<div className="detail-body">{selected.poster&&<img className="detail-poster" src={selected.poster} alt="" referrerPolicy="no-referrer"/>}<div className="detail-text"><p className="eyebrow">{selected.demo?'ОТКРЫТОЕ КИНО · ДЕМО':'БЕСПЛАТНЫЙ ИСТОЧНИК'}</p><h2>{details?.item.title||selected.title}</h2><p>{selected.original} {selected.year?`· ${selected.year}`:''}</p><p>{selected.plot}</p><div className="detail-actions"><button className="primary" disabled={loading||!episode} onClick={()=>setPlaying(true)}>{loading?<LoaderCircle className="spin" size={16}/>:<Play size={16} fill="currentColor"/>}{selected.demo?'Смотреть демофильм':'Смотреть'}</button><button className="filter" onClick={()=>toggleSave(selected.id)}>{saved.includes(selected.id)?'✓ В моём списке':'+ Буду смотреть'}</button></div><p className="notice">{selected.demo?'Демонстрационный фильм: оригинал и субтитры, без русской озвучки.':'Минимум 1080p. Русская озвучка, оригинал и субтитры проверяются при запуске.'}</p></div></div>}{playing&&<h2 className="watch-title">{details?.item.title||selected.title}{episode&&episode.season>0?` · Сезон ${episode.season}, серия ${episode.number}`:''}</h2>}{details&&details.episodes.length>1&&<div><label className="season-label">Сезон <select className="filter" value={episode?.season} onChange={e=>{setStream(null);setEpisode(details.episodes.find(x=>x.season===Number(e.target.value))??null);}}>{[...new Set(details.episodes.map(e=>e.season))].map(s=><option key={s} value={s}>{s}</option>)}</select></label><div className="episode-list">{details.episodes.filter(e=>e.season===episode?.season).map(e=><button className={'filter '+(e.key===episode?.key?'selected':'')} key={e.key} aria-pressed={e.key===episode?.key} title={e.title} onClick={()=>{setStream(null);setEpisode(e);}}>Серия {e.number}</button>)}</div></div>}{loading&&<p className="notice" role="status">Загружаем данные источника…</p>}{error&&<div className="error" role="alert">{error}<div><button className="filter" onClick={()=>setLoadAttempt(v=>v+1)}>Повторить</button></div></div>}{stream&&episode&&<Player key={`${selected.id}:${episode.key}`} data={stream} storageKey={`kadr:progress:${selected.id}:${episode.key}`} onProgress={updateProgress} onEnded={()=>{const index=details?.episodes.findIndex(e=>e.key===episode.key)??-1;const next=details?.episodes[index+1];if(next){setStream(null);setEpisode(next);}}}/>}</>}</DialogContent></Dialog>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog" showCloseButton={false}><DialogClose className="modal-close" aria-label="Закрыть настройки"><X size={20}/></DialogClose><DialogTitle>Источник и просмотр</DialogTitle><DialogDescription>Только бесплатные источники. Без регистрации и платной подписки в этом приложении.</DialogDescription><div className="settings-copy"><p><strong>Collaps</strong> — внешний источник. Каталог на главной — стартовая подборка; другой фильм можно открыть по ID Кинопоиска.</p><label htmlFor="movie-id">ID фильма или сериала</label><div className="id-form"><input id="movie-id" inputMode="numeric" placeholder="Например, 447301" value={idQuery} onChange={e=>setIdQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void openId();}}/><button className="primary" onClick={()=>void openId()}>Открыть</button></div>{error&&<p className="error">{error}</p>}<p><strong>Качество:</strong> минимум Full HD (ширина от 1920 пикселей), 4K — если источник его предоставляет. Потоки меньшего разрешения не запускаются.</p><p><strong>Дорожки:</strong> выбор доступной русской озвучки, оригинала и субтитров — в меню плеера. Для сериала проверка выполняется отдельно для каждой серии.</p><p>Наличие фильма в подборке не гарантирует доступный поток. Проверенные сейчас популярные фильмы у источника ограничены 720p; сайт честно остановит их запуск.</p><p><strong>Проверка плеера:</strong> «Синтел» — открытый демофильм Blender с 4K-потоком. Русской озвучки в нём нет.</p><p>Закладки и прогресс хранятся только в этом браузере. Видео поступает непосредственно с CDN источника.</p><button className="filter" onClick={()=>{try{for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith('kadr:'))localStorage.removeItem(key);}}catch{}setHistory([]);setSaved([]);}}>Очистить закладки и историю</button><p><a href="https://github.com/yumata/lampa-source/blob/master/plugins/online/collaps.js" className="link" target="_blank" rel="noreferrer">Описание интеграции источника</a> · <a href="/credits" className="link">Авторы и материалы</a></p></div></DialogContent></Dialog>
 </main>;
}
