'use client';
import {useEffect,useState} from 'react';
import AdminDashboard from './admin-dashboard';
type User={id:number;username:string;role:string};
type Invite={id:number;created_at:number;expires_at:number;used_at:number|null;revoked_at:number|null;used_by:string|null};
export default function Admin(){
 const [users,setUsers]=useState<User[]>([]),[invites,setInvites]=useState<Invite[]>([]),[link,setLink]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function reload(){const results=await Promise.all(['/api/users','/api/invitations'].map(async path=>{const r=await fetch(path);if(r.status===401){location.replace('/login');throw new Error('Требуется вход.');}if(!r.ok)throw new Error('Не удалось загрузить участников.');return r.json();}));setUsers(results[0]);setInvites(results[1]);}
 useEffect(()=>{reload().catch(e=>setMessage(e.message));},[]);
 async function act(method:string,body:object,path='/api/users'){setBusy(true);setMessage('');try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.url)setLink(d.url);setMessage('Готово');await reload();return true;}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');return false;}finally{setBusy(false);}}
 return <main className="anime-app"><header><a className="brand" href="/">кадр<span> / anime</span></a><a href="/">← К аниме</a></header><AdminDashboard/><h1>Свои люди</h1>
 <section className="invite-panel"><button className="primary" disabled={busy} onClick={()=>void act('POST',{},'/api/invitations')}>Создать приглашение</button><p className="muted">Одна ссылка — один аккаунт. Действует 7 дней.</p>
 {link&&<div className="invite-link"><label>Ссылка для друга<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button disabled={busy} onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Ссылка скопирована');}catch{setMessage('Выделите и скопируйте ссылку вручную.');}}}>Скопировать</button><p className="muted">Сохраните ссылку: после перезагрузки она не показывается.</p></div>}
 <div>{invites.map(i=>{const active=!i.used_at&&!i.revoked_at&&i.expires_at>Date.now();return <div className="invite-row" key={i.id}><span>Приглашение #{i.id}</span><small>{i.used_at?`Использовано${i.used_by?' · '+i.used_by:''}`:i.revoked_at?'Отозвано':active?`До ${new Date(i.expires_at).toLocaleString('ru-RU')}`:'Истекло'}</small>{active&&<button disabled={busy} onClick={async()=>{if(await act('DELETE',{id:i.id},'/api/invitations'))setLink('');}}>Отозвать</button>}</div>;})}</div></section>
 <p role="status">{message}</p><div className="users">{users.map(u=><div className="user-row" key={u.id}><strong>{u.username}</strong>{u.role==='admin'?<span>Суперадминистратор</span>:<><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const password=new FormData(form).get('password');if(await act('PATCH',{id:u.id,password}))form.reset();}}><input aria-label={`Новый пароль для ${u.username}`} name="password" type="password" required minLength={6} maxLength={128} placeholder="Новый пароль" autoComplete="new-password"/><button disabled={busy}>Сменить пароль</button></form><button className="danger" disabled={busy} onClick={()=>{if(confirm(`Удалить аккаунт ${u.username}?`))void act('DELETE',{id:u.id});}}>Удалить</button></>}</div>)}</div></main>;
}
