'use client';
import {useEffect,useState} from 'react';
import {Activity,Users,Play,Clock,RefreshCw} from 'lucide-react';
type Dashboard={generatedAt:number;startedAt:number;from:number;to:number;step:number;totals:{activeUsers:number;activeMinutes:number;watchMinutes:number;totalUsers:number;newUsers:number};online:{id:number;username:string;seenAt:number;path:string;title:string;playing:number}[];series:{time:number;users:number;watchMinutes:number}[];titles:{title:string;minutes:number;users:number}[];users:{id:number;username:string;minutes:number;watchMinutes:number;lastSeen:number}[]};
const date=(n:number)=>new Date(n).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const duration=(n:number)=>n>=60?`${Math.floor(n/60)} ч ${n%60} мин`:`${n} мин`;
function localDate(n:number){const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export default function AdminDashboard(){
 const [period,setPeriod]=useState('24'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[range,setRange]=useState<{from:number;to:number}|null>(null),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{
  let active=true;const controller=new AbortController();
  async function load(){
   const end=Date.now(),start=end-Number(period)*3600000;
   const selected=period==='custom'?range:{from:start,to:end};
   if(!selected)return;
   try{const r=await fetch(`/api/admin/dashboard?from=${selected.from}&to=${selected.to}`,{cache:'no-store',signal:controller.signal});if(r.status===401){location.replace('/login');return;}const value=await r.json();if(!r.ok)throw new Error(value.error||'Не удалось загрузить статистику.');if(active){setData(value);setError('');}}
   catch(e){if(active)setError(e instanceof Error?e.message:'Не удалось загрузить статистику.');}finally{if(active)setLoading(false);}
  }
  void load();const timer=setInterval(()=>void load(),30000);
  return()=>{active=false;controller.abort();clearInterval(timer);};
 },[period,range,refresh]);
 const bars:Dashboard['series']=[];
 if(data){const rows=new Map(data.series.map(row=>[row.time,row]));for(let time=Math.floor(data.from/data.step)*data.step;time<data.to;time+=data.step)bars.push(rows.get(time)||{time,users:0,watchMinutes:0});}
 const max=Math.max(1,...bars.map(b=>b.users));
 return <section className="dashboard" aria-label="Статистика пользователей">
  <div className="dash-heading"><div><p className="dash-eyebrow">ПУЛЬТ УПРАВЛЕНИЯ</p><h1>Активность клуба</h1><p className="muted">Кто здесь сейчас и как проходит просмотр.</p></div><button className="dash-refresh" onClick={()=>{setLoading(true);setRefresh(v=>v+1);}} disabled={loading}><RefreshCw size={16}/> {loading?'Загрузка…':'Обновить'}</button></div>
  <div className="dash-filters"><div className="dash-presets">{[['24','24 часа'],['168','7 дней'],['720','30 дней']].map(([value,label])=><button key={value} aria-pressed={period===value} onClick={()=>{if(period!==value){setLoading(true);setPeriod(value);}}}>{label}</button>)}<button aria-pressed={period==='custom'} onClick={()=>{const end=Date.now();setFrom(localDate(end-86400000));setTo(localDate(end));setRange({from:end-86400000,to:end});setPeriod('custom');}}>Свой период</button></div><span className="muted">Обновление каждые 30 сек.</span></div>
  {period==='custom'&&<form className="dash-range" onSubmit={e=>{e.preventDefault();const a=new Date(from).getTime(),b=new Date(to).getTime();if(!Number.isFinite(a)||!Number.isFinite(b)||a>=b||a<Date.now()-90*86400000||b>Date.now()){setError('Укажите начало раньше конца, в пределах последних 90 дней и не в будущем.');return;}setRange({from:a,to:b});}}><label>С<input required type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По<input required type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="primary">Применить</button><small className="muted">Время вашего устройства</small></form>}
  {error&&<p className="dash-error" role="alert">{error} {data&&'Ниже — последние загруженные данные.'}</p>}
  {!data&&loading&&<p role="status">Загружаем активность…</p>}
  {data&&<>
   <div className="dash-cards">{[{label:'Сейчас на сайте',value:data.online.length,detail:`${data.online.filter(u=>u.playing).length} смотрят видео`,icon:Activity},{label:'Активных за период',value:data.totals.activeUsers,detail:`${data.totals.totalUsers} участников всего · +${data.totals.newUsers||0} новых`,icon:Users},{label:'Время на сайте ≈',value:duration(data.totals.activeMinutes),detail:'Сумма активных минут участников',icon:Clock},{label:'Время просмотра ≈',value:duration(data.totals.watchMinutes),detail:'По сигналам работающего плеера',icon:Play}].map(c=><article className="dash-card" key={c.label}><div><span>{c.label}</span><c.icon size={18}/></div><strong>{c.value}</strong><small>{c.detail}</small></article>)}</div>
   <div className="dash-panel"><div className="dash-panel-title"><h2><span className="dash-dot"/> Сейчас на сайте</h2><span className="muted">Сигнал за последние 90 сек.</span></div>{data.online.length===0?<p className="dash-empty">Сейчас никого нет на сайте.</p>:<div className="dash-table-wrap"><table><thead><tr><th>Участник</th><th>Активность</th><th>Последний сигнал</th></tr></thead><tbody>{data.online.map(u=><tr key={u.id}><td><strong>{u.username}</strong></td><td>{u.playing?<><span className="dash-status">Смотрит</span> {u.title||'Видео'}</>:<><span className="dash-status neutral">На сайте</span> {u.path==='/admin'?'Админка':u.path==='/'?'Каталог':u.path}</>}</td><td>{date(u.seenAt)}</td></tr>)}</tbody></table></div>}</div>
   <div className="dash-panel"><div className="dash-panel-title"><h2>Активные участники</h2><span className="muted">{data.step===3600000?'По часам':'По дням'} · {date(data.from)} — {date(data.to)}</span></div>{data.totals.activeUsers===0?<p className="dash-empty">За этот период активности пока нет.</p>:<><div className="dash-chart" role="img" aria-label={`Участники по времени. Максимум ${max}. Точные значения доступны в таблице ниже.`}>{bars.map(b=><div className="dash-bar-slot" key={b.time} title={`${date(b.time)}: ${b.users} участников`}><div style={{height:`${b.users/max*100}%`}}/></div>)}</div><div className="dash-chart-axis"><span>{date(data.from)}</span><span>До {max} участников за интервал</span><span>{date(data.to)}</span></div><details><summary>Данные графика</summary><div className="dash-table-wrap"><table><thead><tr><th>Интервал с</th><th>Участники</th><th>Просмотр ≈</th></tr></thead><tbody>{bars.map(b=><tr key={b.time}><td>{date(b.time)}</td><td>{b.users}</td><td>{duration(b.watchMinutes)}</td></tr>)}</tbody></table></div></details></>}</div>
   <div className="dash-columns"><div className="dash-panel"><h2>Популярные тайтлы</h2><p className="muted">По минутам просмотра · топ 10</p>{!data.titles.length?<p className="dash-empty">Просмотров за период пока нет.</p>:data.titles.map((t,i)=><div className="dash-title-row" key={t.title}><span className="muted">{String(i+1).padStart(2,'0')}</span><strong>{t.title}<small>{t.users} участн.</small></strong><span>{duration(t.minutes)}</span></div>)}</div><div className="dash-panel"><h2>Участники за период</h2><p className="muted">По активности · до 100 участников</p>{!data.users.length?<p className="dash-empty">Активность появится после посещений.</p>:<div className="dash-table-wrap"><table><thead><tr><th>Участник</th><th>На сайте ≈</th><th>Смотрел ≈</th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td>{u.username}</td><td>{duration(u.minutes)}</td><td>{duration(u.watchMinutes)}</td></tr>)}</tbody></table></div>}</div></div>
   <p className="dash-note muted">Данные с {date(data.startedAt)} · храним 90 дней · обновлено {date(data.generatedAt)}. Активность — открытая видимая вкладка или воспроизведение видео. Время приблизительное: каждая минута с сигналом считается один раз на участника, даже с нескольких устройств. Закрытая вкладка исчезает из списка в течение 90 секунд.</p>
  </>}
 </section>;
}
