'use client';
import {useEffect,useState} from 'react';
type User={id:number;username:string;role:string};
export default function Admin(){
 const [users,setUsers]=useState<User[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function reload(){const r=await fetch('/api/users');if(r.status===401){location.replace('/login');return;}if(!r.ok)throw new Error('Не удалось загрузить пользователей.');setUsers(await r.json());}
 useEffect(()=>{reload().catch(e=>setMessage(e.message));},[]);
 async function act(method:string,body:object){setBusy(true);setMessage('');try{const r=await fetch('/api/users',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Готово');await reload();return true;}catch(e){setMessage(e instanceof Error?e.message:'Ошибка');return false;}finally{setBusy(false);}}
 return <main className="anime-app"><header><a className="brand" href="/">кадр<span> / anime</span></a><a href="/">← К аниме</a></header><h1>Свои люди</h1><p className="muted">Создавайте аккаунты для друзей. После удаления аккаунта или смены пароля его сессии перестанут действовать.</p><form className="admin-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(await act('POST',data))form.reset();}}><label>Логин<input name="username" required pattern="[A-Za-z0-9_]{3,32}" placeholder="friend" autoComplete="off"/></label><label>Пароль<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password" placeholder="Не менее 12 символов"/></label><button className="primary" disabled={busy}>Создать аккаунт</button></form><p role="status">{message}</p><div className="users">{users.map(u=><div className="user-row" key={u.id}><strong>{u.username}</strong>{u.role==='admin'?<span>Суперадминистратор</span>:<><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const password=new FormData(form).get('password');if(await act('PATCH',{id:u.id,password}))form.reset();}}><input aria-label={`Новый пароль для ${u.username}`} name="password" type="password" required minLength={12} maxLength={128} placeholder="Новый пароль" autoComplete="new-password"/><button disabled={busy}>Сменить пароль</button></form><button className="danger" disabled={busy} onClick={()=>{if(confirm(`Удалить аккаунт ${u.username}?`))void act('DELETE',{id:u.id});}}>Удалить</button></>}</div>)}</div></main>;
}
