'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import SearchSuggestions from '@/components/search-suggestions';
import {useRouter} from 'next/navigation';
import {watchUrl,type WatchPage} from '@/lib/watch-page';
import {Player} from '@/components/cinema/player';
import {getProgress,clock,type WatchRecord} from '@/lib/watch';
import type {Playback} from '@/lib/cinema/types';
import {providerSegments} from '@/lib/cinema/segments';
type Item={id:string;key:string;title:string;thumbnail:string};
type Episode={id:string;ordinal:number;title:string;opening?:{start:number;stop:number};ending?:{start:number;stop:number}};
type Source={id:string;title:string;player:string};
type Details={title:string;description:string;episodes:Episode[]};
async function api(path:string,signal?:AbortSignal){const r=await fetch('/api/extractor/'+path,{signal});if(r.status===401){location.replace('/login');throw new Error('Сессия истекла.');}const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка источника');return d;}
export default function ExtractorBrowser({userId,resume,watchPage}:{userId:number;resume?:WatchRecord|null;watchPage?:WatchPage}){
 const router=useRouter();
 const [providers,setProviders]=useState<{id:string;title:string}[]>([]),[provider,setProvider]=useState(watchPage?.provider||'yummy_anime');
 const open=useCallback((i:Item,p=provider)=>router.push(watchUrl({provider:p,id:i.id,key:i.key,title:i.title,poster:i.thumbnail})),[provider,router]);
 const suggest=useCallback(async(query:string,signal:AbortSignal)=>{const data=await api(`search/${provider}?q=${encodeURIComponent(query)}`,signal);return (data.items as Item[]).map(i=>({id:i.id,title:i.title,image:i.thumbnail,href:watchUrl({provider,id:i.id,key:i.key,title:i.title,poster:i.thumbnail})}));},[provider]);
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[retry,setRetry]=useState(0),[items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [item,setItem]=useState<Item|null>(watchPage?{id:watchPage.id,key:watchPage.key||watchPage.id,title:watchPage.title||"Аниме",thumbnail:watchPage.poster||""}:null),[details,setDetails]=useState<Details|null>(null),[episode,setEpisode]=useState<Episode|null>(null),[sources,setSources]=useState<Source[]>([]),[source,setSource]=useState(''),[playback,setPlayback]=useState<Playback|null>(null),[detailError,setDetailError]=useState(''),[stage,setStage]=useState(''),[records,setRecords]=useState<WatchRecord[]>([]);
 const [targetProvider,setTargetProvider]=useState('yummy_anime'),[seasonQuery,setSeasonQuery]=useState(''),[related,setRelated]=useState<Item[]>([]),[relatedBusy,setRelatedBusy]=useState(false),[relatedError,setRelatedError]=useState('');
 const preferred=useRef(''),pendingResume=useRef<WatchRecord|null>(null),relatedAbort=useRef<AbortController|null>(null);
 const titleKey=item?`${provider}:${item.key}`:'';
 useEffect(()=>{if(!resume)return;pendingResume.current=resume;setItem(null);setProvider(resume.provider);setInput(resume.title);setQuery(resume.title);setRetry(v=>v+1);},[resume]);
 useEffect(()=>{const c=new AbortController();api('providers',c.signal).then(d=>setProviders(d.items)).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[retry]);
 useEffect(()=>{if(watchPage)return;const c=new AbortController();setBusy(true);setError('');setItems([]);api(`search/${provider}?q=${encodeURIComponent(query)}`,c.signal).then(d=>{setItems(d.items);if(pendingResume.current){const found=d.items.find((x:Item)=>`${provider}:${x.key}`===pendingResume.current?.titleKey);pendingResume.current=null;if(found)open(found);else setError('Релиз изменился у источника. Выберите его в результатах поиска.');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[provider,query,retry,open,watchPage]);
 useEffect(()=>{if(!item)return;const c=new AbortController();setStage('Загрузка серий…');setDetails(null);setEpisode(null);setSources([]);setPlayback(null);setDetailError('');setRecords([]);setTargetProvider(provider);setSeasonQuery(item.title);setRelated([item]);setRelatedError('');preferred.current='';Promise.all([api('anime/'+item.id,c.signal),getProgress(titleKey,c.signal)]).then(([d,rows])=>{setDetails(d);setRecords(rows);const last=rows[0];preferred.current=last?.sourceLabel||'';const index=d.episodes.findIndex((e:Episode)=>String(e.ordinal)===last?.episodeKey);setEpisode(d.episodes[index>=0?(last.watched&&d.episodes[index+1]?index+1:index):0]||null);}).catch(e=>{if(!c.signal.aborted)setDetailError(e.message);}).finally(()=>{if(!c.signal.aborted)setStage('');});return()=>c.abort();},[item,provider,titleKey]);
 useEffect(()=>{if(!titleKey)return;let alive=true;const load=()=>getProgress(titleKey).then(rows=>{if(alive)setRecords(rows);}).catch(()=>{});window.addEventListener('watch-progress',load);return()=>{alive=false;window.removeEventListener('watch-progress',load);};},[titleKey]);
 useEffect(()=>{setPlayback(null);setSources([]);setSource('');if(!episode)return;const c=new AbortController();setStage('Загрузка переводов…');setDetailError('');api('sources/'+episode.id,c.signal).then(d=>{setSources(d.items);setSource(d.items.find((s:Source)=>s.title===preferred.current)?.id||d.items[0]?.id||'');}).catch(e=>{if(!c.signal.aborted)setDetailError(e.message);}).finally(()=>{if(!c.signal.aborted)setStage('');});return()=>c.abort();},[episode]);
 useEffect(()=>{setPlayback(null);if(!source)return;const c=new AbortController();setStage('Загрузка видео…');setDetailError('');api('playback/'+source,c.signal).then(data=>setPlayback({...data,segments:providerSegments(episode)})).catch(e=>{if(!c.signal.aborted)setDetailError(e.message);}).finally(()=>{if(!c.signal.aborted)setStage('');});return()=>c.abort();},[source,episode]);
 useEffect(()=>()=>relatedAbort.current?.abort(),[]);
 async function findRelated(nextProvider=targetProvider){relatedAbort.current?.abort();const c=new AbortController();relatedAbort.current=c;setRelatedBusy(true);setRelatedError('');setRelated([]);try{const d=await api(`search/${nextProvider}?q=${encodeURIComponent(seasonQuery)}`,c.signal);if(!c.signal.aborted)setRelated(d.items);}catch(e){if(!c.signal.aborted)setRelatedError(e instanceof Error?e.message:'Ошибка поиска');}finally{if(!c.signal.aborted)setRelatedBusy(false);}}
 function close(){relatedAbort.current?.abort();setItem(null);setEpisode(null);setPlayback(null);}
 const next=details?.episodes[(details.episodes.findIndex(e=>e.id===episode?.id)??-1)+1];
 const controls=<><label>Источник<select value={targetProvider} onChange={e=>{setTargetProvider(e.target.value);void findRelated(e.target.value);}}>{providers.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Сезон / релиз<select aria-label="Сезон или релиз" value={targetProvider===provider?item?.id||'':''} disabled={relatedBusy} onChange={e=>{const found=related.find(x=>x.id===e.target.value);if(found){open(found,targetProvider);}}}><option value="" disabled>Выберите релиз</option>{related.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><details className="watch-season-search"><summary>Найти другой сезон</summary><div><input aria-label="Название сезона" value={seasonQuery} maxLength={100} onChange={e=>setSeasonQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void findRelated();}}/><button disabled={relatedBusy} onClick={()=>void findRelated()}>{relatedBusy?'Поиск…':'Найти'}</button></div></details>{relatedError&&<p role="alert">{relatedError}</p>}<label>Серия<select value={episode?.id||''} onChange={e=>setEpisode(details?.episodes.find(x=>x.id===e.target.value)||null)}>{details?.episodes.map(e=>{const row=records.find(r=>r.episodeKey===String(e.ordinal));return <option key={e.id} value={e.id}>{row?.watched?'✓ ':''}{e.ordinal} · {e.title}{row&&!row.watched?` — ${clock(row.position)}`:''}</option>;})}</select></label><label>Озвучка / субтитры<select value={source} disabled={!sources.length} onChange={e=>{preferred.current=sources.find(s=>s.id===e.target.value)?.title||'';setSource(e.target.value);}}>{sources.map((s,i)=><option key={s.id} value={s.id}>{s.title} · {s.player||`плеер ${i+1}`}</option>)}</select></label></>;
 return <section>{!watchPage&&<><form className="extractor-search" onSubmit={e=>{e.preventDefault();setQuery(input.trim());setRetry(v=>v+1);}}><label>Источник<select value={provider} onChange={e=>{close();setProvider(e.target.value);}}>{providers.length?providers.map(p=><option key={p.id} value={p.id}>{p.title}</option>):<option value="yummy_anime">YummyAnime</option>}</select></label><SearchSuggestions key={provider} value={input} onChange={setInput} load={suggest} onSelect={i=>router.push(i.href)} onSearch={q=>{setQuery(q);setRetry(v=>v+1);}}/><button className="primary" disabled={busy}>Найти</button></form>
 {busy?<p role="status">Загрузка…</p>:<>{error&&<div className="error" role="alert">{error}<button onClick={()=>setRetry(v=>v+1)}>Повторить</button></div>}<div className="anime-grid">{items.map(i=><button className="anime-card" key={i.id} onClick={()=>open(i)}>{i.thumbnail?<img src={i.thumbnail} loading="lazy" alt=""/>:<div className="poster-placeholder"/>}<h2>{i.title}</h2></button>)}</div></>}
 {!busy&&!error&&!items.length&&<p>Ничего не найдено.</p>}
 </>}
 {watchPage&&<div className="watch-page"><Link className="watch-back" href="/">← В каталог</Link><h1 className="watch-page-title">{details?.title||item?.title||'Аниме'}</h1>

 {item&&<Player key={`${provider}:${item.key}:${episode?.ordinal??'loading'}`} data={playback} storageKey={`extractor:${userId}:${titleKey}:${episode?.ordinal}`} watch={episode?{titleKey,episodeKey:String(episode.ordinal),title:item.title,provider,episode:episode.ordinal,poster:item.thumbnail,sourceLabel:sources.find(s=>s.id===source)?.title||''}:undefined} title={episode?`Серия ${episode.ordinal}`:''} controls={controls} loading={stage} externalError={detailError||(!stage&&episode&&!sources.length?'Нет переводов для этой серии.':'')} autoPlay onEnded={()=>{if(next)setEpisode(next);}} onNext={next?()=>setEpisode(next):undefined}/>}
 {details?.description&&<details className="watch-description"><summary>Описание</summary><p>{details.description.replace(/<[^>]*>/g,'')}</p></details>}
 </div>}</section>;
}
